name: Hello Web Slot Deployment

# Triggers
on: [push, workflow_dispatch]

# Environment variables 
env:
  RESOURCE-GROUP: gihubyamlweb_group
  LOCATION: westeurope
  TEMPLATE-PATH: .azure/bicep/
  SUBSCRIPTION-ID: 961f09e9-f925-4a31-a33b-aaeedd12630c
  WEBAPP-NAME: githubyamluwe
  WEBAPP_PACKAGE_PATH: './published'

# Jobs
jobs:
  #Build, test and publish .net web project in repository
  buildanddeploy:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest    
    steps:
    
    #checkout the repository
    - name: Clone Repo
      uses: actions/checkout@v2     
    # prepare runner for desired .net version SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: false
        
    # Build and Publish the .NET project
    - name: Restore 
      run: dotnet restore 
    - name: Build 
      run: dotnet build ./HelloWeb.sln --configuration Release --no-restore
    - name: Package 
      run: dotnet publish ./HelloWeb.csproj --configuration Release --no-build --output ${{ env.WEBAPP_PACKAGE_PATH }}
              
    # Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
               
    # Publish website to Azure App Service (WebApp)
    - name: Publish Website to WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP-NAME  }}
        slot-name: staging
        package: ${{ env.WEBAPP_PACKAGE_PATH }}
