name: Hello Web CI CD

# Triggers
on: [push, workflow_dispatch]

# Environment variables 
env:
  RESOURCE-GROUP: rgDemoEShopOnWeb
  LOCATION: westeurope
  TEMPLATE-PATH: .azure/bicep/
  SUBSCRIPTION-ID: 961f09e9-f925-4a31-a33b-aaeedd12630c
  WEBAPP-NAME: app-helloweb

# Jobs
jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    #checkout the repository
    - uses: actions/checkout@v2
    #prepare runner for desired .net version SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: false
    #Build/Test/Publish the .net project
    - name: Build with dotnet
      run: dotnet build ./HelloWeb.sln --configuration Release
    #- name: Test with dotnet
    #  run: dotnet test ./eShopOnWeb.sln --configuration Release
    - name: dotnet publish
      run: dotnet publish ./HelloWeb.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
    # upload the published website code artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
        
    # upload the bicep template as artifacts for next job
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bicep-templates
        path: ${{ env.TEMPLATE-PATH }}
        
  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    
    #Download the publish files created in previous job
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app
        path: .net-app
  
    #Download the bicep templates from previous job
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: bicep-templates
        path: bicep-templates
        
   #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
           
    # Deploy Azure WebApp using Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION-ID }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: bicep-templates/webapp-rg.bicep
        parameters: 'webAppName=${{ env.WEBAPP-NAME }} resourceGroupName=${{ env.RESOURCE-GROUP }} location=${{ env.LOCATION }}'
        failOnStdErr: false   
    
    # Publish website to Azure App Service (WebApp)
    - name: Publish Website to WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP-NAME  }}
        package: .net-app
